### ISSUE TITLE
UnboundLocalError: local variable 'sql_type' referenced before assignment

### ISSUE THREAD

**Issue by selin-tropos** [jackscodemonkey/sphinx-sql#1]
I'm trying to do autodoc with .sql files using sphinx-sql. I have created an `autosql.rst` file in the same directory as my `index.rst` file. I have added the code snippets you provided.
This one I added in my `conf.py` file
```
extensions = [
'sphinx_sql.sphinx_sql',
]
```
This I added in the `index.rst` file
```
.. toctree::
:maxdepth: 2
:caption: Navigation:

autosql
```
And this was added to the new `autosql.rst` file
```
SQL Documentation
^^^^^^^^^^^^^^^^^

.. autosql::
    :sqlsource: ../macros
```

After running `make html`, I get the next error: `UnboundLocalError: local variable 'sql_type' referenced before assignment`.
I'll also add the log file in case this would be useful.
```
# Sphinx version: 3.3.1
# Python version: 3.8.6 (CPython)
# Docutils version: 0.15.2 release
# Jinja2 version: 2.11.2
# Last messages:
#   Sphinx v3.3.1 start op
#   building [mo]: targets for 0 po files that are out of date
#   building [html]: targets for 3 source files that are out of date
#   updating environment:
#   [new config]
#   3 added, 0 changed, 0 removed
#   reading sources... [ 33%] autosql
# Loaded extensions:
#   sphinx.ext.mathjax (3.3.1) from /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/sphinx/ext/mathjax.py
#   sphinxcontrib.applehelp (1.0.2) from /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/sphinxcontrib/applehelp/__init__.py
#   sphinxcontrib.devhelp (1.0.2) from /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/sphinxcontrib/devhelp/__init__.py
#   sphinxcontrib.htmlhelp (1.0.3) from /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/sphinxcontrib/htmlhelp/__init__.py
#   sphinxcontrib.serializinghtml (1.1.4) from /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/sphinxcontrib/serializinghtml/__init__.py
#   sphinxcontrib.qthelp (1.0.3) from /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/sphinxcontrib/qthelp/__init__.py
#   alabaster (0.7.12) from /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/alabaster/__init__.py
#   sphinx_sql.sphinx_sql (1.0) from /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/sphinx_sql/sphinx_sql.py
#   sphinxcontrib.jinja (unknown version) from /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/sphinxcontrib/jinja.py
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/sphinx/cmd/build.py", line 280, in build_main
    app.build(args.force_all, filenames)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/sphinx/application.py", line 352, in build
    self.builder.build_update()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/sphinx/builders/__init__.py", line 297, in build_update
    self.build(to_build,
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/sphinx/builders/__init__.py", line 311, in build
    updated_docnames = set(self.read())
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/sphinx/builders/__init__.py", line 418, in read
    self._read_serial(docnames)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/sphinx/builders/__init__.py", line 439, in _read_serial
    self.read_doc(docname)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/sphinx/builders/__init__.py", line 479, in read_doc
    doctree = read_doc(self.app, self.env, self.env.doc2path(docname))
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/sphinx/io.py", line 223, in read_doc
    pub.publish()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/docutils/core.py", line 216, in publish
    self.document = self.reader.read(self.source, self.parser,
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/sphinx/io.py", line 128, in read
    self.parse()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/docutils/readers/__init__.py", line 77, in parse
    self.parser.parse(self.input, document)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/sphinx/parsers.py", line 102, in parse
    self.statemachine.run(inputlines, document, inliner=self.inliner)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/docutils/parsers/rst/states.py", line 170, in run
    results = StateMachineWS.run(self, input_lines, input_offset,
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/docutils/statemachine.py", line 238, in run
    context, next_state, result = self.check_line(
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/docutils/statemachine.py", line 460, in check_line
    return method(match, context, next_state)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/docutils/parsers/rst/states.py", line 2771, in underline
    self.section(title, source, style, lineno - 1, messages)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/docutils/parsers/rst/states.py", line 327, in section
    self.new_subsection(title, lineno, messages)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/docutils/parsers/rst/states.py", line 393, in new_subsection
    newabsoffset = self.nested_parse(
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/docutils/parsers/rst/states.py", line 281, in nested_parse
    state_machine.run(block, input_offset, memo=self.memo,
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/docutils/parsers/rst/states.py", line 196, in run
    results = StateMachineWS.run(self, input_lines, input_offset)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/docutils/statemachine.py", line 238, in run
    context, next_state, result = self.check_line(
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/docutils/statemachine.py", line 460, in check_line
    return method(match, context, next_state)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/docutils/parsers/rst/states.py", line 2344, in explicit_markup
    nodelist, blank_finish = self.explicit_construct(match)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/docutils/parsers/rst/states.py", line 2356, in explicit_construct
    return method(self, expmatch)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/docutils/parsers/rst/states.py", line 2098, in directive
    return self.run_directive(
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/docutils/parsers/rst/states.py", line 2148, in run_directive
    result = directive_instance.run()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/sphinx_sql/sphinx_sql.py", line 252, in run
    core = self.extract_core_text(file)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/sphinx_sql/sphinx_sql.py", line 89, in extract_core_text
    if sql_type[1]:
UnboundLocalError: local variable 'sql_type' referenced before assignment
```

**Comment by jackscodemonkey** [comment]
Thanks, I've had a look and I'm definitely not checking sql_type properly. That should be a quick fix to turn around.

Fixing this did surface a problem I hadn't tested for but may be a valid use case.
If the file structure is a DDL create it should be able to parse the name / object type, I initially intended to ignore what looks like DML. If there is a use case for documenting a DML object, I could add optional parameters for the comment doc string that would override the regular expressions that tries to dynamically find the name and type. 

Could you provide a sanitized example of one of your sql files you are trying to parse?

**Comment by selin-tropos** [comment]
This is just an example model from dbt-tutorial
```
/*
    Welcome to your first dbt model!
    Did you know that you can also configure models directly within SQL files?
    This will override configurations stated in dbt_project.yml

    Try changing "table" to "view" below
*/

{{ config(materialized='table') }}

with source_data as (

    select 1 as id
    union all
    select null as id

)

select *
from source_data

/*
    Uncomment the line below to remove records with null `id` values
*/

-- where id is not null
```

**Comment by jackscodemonkey** [comment]
I've added the ability to process DML style files. 
It does require tagging the comment at minimum with the keywords 
Object Name: 
and 
Object Type: 

Those keywords are needed when processing the dictionary of items for sphinx to write out to the document. 
If they cannot be found sphinx-sql will ignore the file. In a normal SQL object I dynamically find values for those keys, so this only applies to DML style files.

Using your example the comments would look like the screenshot below. The section name of DML is arbitrary, you could name it anything you like as long as its a single word. At a minimum, you'd want Object Name:, Object Type: and Purpose: to be useful. You can add other keywords like I did with ChangeLog: and they will also be collected. 

Release 1.1 has been uploaded to pypi, give it a try and let me know if it works.

```
/*
Object Name: freeform.sqlfiles
Object Type: DML

Purpose:
    Welcome to your first dbt model!
    Did you know that you can also configure models directly within SQL files?
    This will override configurations stated in dbt_project.yml

    Try changing "table" to "view" below

ChangeLog: 
    Date    |    Author    |    Ticket    |    Modification
    2020-10-26    |  Developer_2  |   T-220    |    Initial Definition

*/

```

The generated document would create a DML section like this:


![Screen Shot 2020-12-01 at 5 39 24 PM](https://user-images.githubusercontent.com/16215050/100817047-422db900-33fc-11eb-9177-56b55ac92b1b.png)

**Comment by jackscodemonkey** [comment]
Closing this issue.
